//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.23 at 10:28:30 PM CEST 
//


package pl.waw.tabor.netbeans.protobuf.generator.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for destinationLanguage.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="destinationLanguage">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="java"/>
 *     &lt;enumeration value="cpp"/>
 *     &lt;enumeration value="python"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "destinationLanguage")
@XmlEnum
public enum DestinationLanguage {

    @XmlEnumValue("java")
    JAVA("java"),
    @XmlEnumValue("cpp")
    CPP("cpp"),
    @XmlEnumValue("python")
    PYTHON("python");
    private final String value;

    DestinationLanguage(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DestinationLanguage fromValue(String v) {
        for (DestinationLanguage c: DestinationLanguage.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
