//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.23 at 10:28:30 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tabor.waw.pl/netbeans/protobuf/generator/jaxb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.waw.tabor.netbeans.protobuf.generator.jaxb;
