//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.23 at 10:28:30 PM CEST 
//


package pl.waw.tabor.netbeans.protobuf.generator.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for generatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="generatorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{http://tabor.waw.pl/netbeans/protobuf/generator/jaxb}destinationLanguage" />
 *       &lt;attribute name="on" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generatorType")
public class GeneratorType {

    @XmlAttribute(required = true)
    protected DestinationLanguage type;
    @XmlAttribute(required = true)
    protected boolean on;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationLanguage }
     *     
     */
    public DestinationLanguage getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationLanguage }
     *     
     */
    public void setType(DestinationLanguage value) {
        this.type = value;
    }

    /**
     * Gets the value of the on property.
     * 
     */
    public boolean isOn() {
        return on;
    }

    /**
     * Sets the value of the on property.
     * 
     */
    public void setOn(boolean value) {
        this.on = value;
    }

}
